### PR TITLE
Fix freeze while hitting the box on Buried

### PR DESCRIPTION
**Pull request by TTS4life**
Turns out having a return statement when checking if the box can give you time bombs is somewhat important to the overall function of Buried. :P

### CODE REVIEW

**Comment by Jbleezy** [comment]
I think that is still going to freeze. Should be an if statement, not while.

**Comment by TTS4life** [comment]
The original `level.special_weapon_magicbox_check` opts to use a while loop when checking for time bomb validity

```c++
buried_special_weapon_magicbox_check( weapon )
{
	if ( weapon == "ray_gun_zm" )
	{
		if ( self has_weapon_or_upgrade( "raygun_mark2_zm" ) )
		{
			return 0;
		}
	}
	if ( weapon == "raygun_mark2_zm" )
	{
		if ( self has_weapon_or_upgrade( "ray_gun_zm" ) )
		{
			return 0;
		}
	}
	while ( weapon == "time_bomb_zm" )
	{
		players = get_players();
		i = 0;
		while ( i < players.size )
		{
			if ( is_player_valid( players[ i ], undefined, 1 ) && players[ i ] is_player_tactical_grenade( weapon ) )
			{
				return 0;
			}
			i++;
		}
	}
	return 1;
}
```

Not really sure what the case is for using while. Maybe it's a more robust way of making sure multiple people don't end up with multiple time bombs? Regardless, I missed the return statement when I first implemented this stuff and it was causing the game to briefly act as though you got a connection interrupted before crashing due to nothing being returned in the `level.special_weapon_magicbox_check`. I tested both with and without the return statement in order to isolate the issue to the fact I missed a line while copy/pasting the code over. Optimizations to pre-existing logic and cleaner code are always welcome however :smile:

**Comment by Jbleezy** [comment]
That is just from the decompiler. It decompiles some of the code incorrectly. It definitely is an if statement internally otherwise it could never give time_bomb_zm. The reason it is crashing is because there is an infinite loop with no wait statement.

**Comment by TTS4life** [comment]
Changed to if, did some extra testing, not sure how good I was at remembering to build after every change.

**Pull request merged**
