### PR TITLE
Make Mark 2 slightly more probable 

### PR DESCRIPTION
**Pull request by TTS4life**
Evens out the Mark 2's odds while also replacing all `level.special_weapon_magicbox_check` declarations into one file for easy tinkering later on. All other checks within this level func are kept default for now.

### CODE REVIEW

**Comment by TTS4life** [comment]
Looking back at the TODO and saw you wanted odds at .5 instead of .33, so I altered the odds a bit. This makes the Mark 2 more probable than it was but not on the same odds of the other weapons available in the box.

**Review by 5and5 — APPROVED** [review]
ty TTS :)

Few things to mention:
-I dont want mrk2 to be equal weight as everything else only 50% less likely
-I want the mod to only be one script to make it easier for people to add and remove it from their game
-I think register_weapon_mods() might be called too early and might be overridden by the map script

**Comment by 5and5** [comment]
TTS mrk2 probability changes

**Review by 5and5 — APPROVED** [review]

**Comment by 5and5** [comment]
i dont know how to use github o.o

**Pull request merged**
